### ISSUE TITLE
FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by 532910** [DDoSolitary/okc-agents#1]
Steps to reproduce:
1. ssh so it will request for autorization
2. just ignore this request
3. terminate ssh with Ctrl-C
4. make another ssh
5. pass or fail a new authorization
6. tap the fist notification with authorization request

```
08-04 01:41:44.590 11328 11328 E AndroidRuntime: Process: org.ddosolitary.okcagent, PID: 11328
08-04 01:41:44.590 11328 11328 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.ddosolitary.okcagent/org.ddosolitary.okcagent.IntentRunnerActivity}: android.content.IntentSender$SendIntentException
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6718)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-04 01:41:44.590 11328 11328 E AndroidRuntime: Caused by: android.content.IntentSender$SendIntentException
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at android.app.Activity.startIntentSenderForResultInner(Activity.java:4844)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at android.app.Activity.startIntentSenderForResult(Activity.java:4813)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.startIntentSenderForResult(FragmentActivity.java:704)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at android.app.Activity.startIntentSenderForResult(Activity.java:4780)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.startIntentSenderForResult(FragmentActivity.java:689)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at org.ddosolitary.okcagent.IntentRunnerActivity.processIntent(IntentRunnerActivity.kt:30)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at org.ddosolitary.okcagent.IntentRunnerActivity.onCreate(IntentRunnerActivity.kt:46)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7144)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7135)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
08-04 01:41:44.590 11328 11328 E AndroidRuntime:        ... 11 more
```

**Comment by DDoSolitary** [comment]
It seems that it's actually a bug/misbehavior of OpenKeychain. OpenKeychain uses the same request code for all of its `PendingIntent`s. As a result, when I make a new authentication request, the old `PendingIntent` will be automatically canceled by Android, making it invalid.

Anyway, I'll see if there's something I can do on my side. Probably I can simply queue up the requests and handle them one by one.
